### ISSUE TITLE
Accesso in scrittura al repo

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/ods2021#1]
Chi vuole essere aggiunto, risponga qui con un "aggiungetemi please"

**Comment by pcmasuzzo** [comment]
Mi si aggiunga, please and thank you :)

**Comment by dataibi** [comment]
"aggiungetemi please"

Il giorno 6 feb 2021, alle ore 12:16, Andrea Borruso <notifications@github.com<mailto:notifications@github.com>> ha scritto:

"aggiungetemi please"
