### ISSUE TITLE
Creare materiale comunicazione "web"

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/ods2021#10]
Al momento il sito è questo <https://ods2021.opendatasicilia.it/>.

È caratterizzato da quest'immagine della Sicilia <https://github.com/opendatasicilia/ods2021/raw/main/assets/img/slider/sicily-satellite_hr.jpg>.
Per noi può essere l'immagine di base su cui costruire:

- [x] immagine per post facebook;
- [x] immagine per post twitter;
- [x] immagine per Instagram;
- [x] cover pagina facebook.

Il font del titolo del sito è [Josefin_Sans.zip](https://github.com/opendatasicilia/ods2021/files/5975729/Josefin_Sans.zip).
Il logo di opendatasicilia è [questo](https://github.com/opendatasicilia/ods2021/files/5975732/logo.opendatasicilia_esagonale_marginato.zip)
Il testo di presentazione del raduno è [questo](https://docs.google.com/document/d/1VVhCa96G4B0o6353QcFr4151_aJgdxo3IN8_-xUbVRk/edit?ts=60210b85#heading=h.9k16s5iw7bsl).

Liberi anche di scegliere tutt'altro e non usare questa immagine. Però si dovrebbe sempre prendere un po' spunto quantomeno dal testo di presentazione del raduno.

L'output si può inserire in [questa cartella](https://drive.google.com/drive/u/0/folders/1FQnxh_egdDEmJqT_95IBsKzS5vi6l89C).
Se è possibile, archiviare l'output anche in formato modificabile, in modo da rendere tutte/i autonome/i.

Sotto un esempio ciao mondo.

GRAZIE!!!

![image](https://user-images.githubusercontent.com/30607/107851277-11f59400-6e09-11eb-98e0-65cb38dd3e21.png)

**Comment by aborruso** [comment]
Ecco un primo output del lavoro di Dennis e Angelo

![image](https://user-images.githubusercontent.com/30607/107863371-3a56b000-6e54-11eb-8e1e-63d498ee4e02.png)

**Comment by dataibi** [comment]
Che bello!!

  Davide


Il giorno 13 feb 2021, alle ore 23:36, Andrea Borruso <notifications@github.com> ha scritto:

﻿

Ecco un primo output del lavoro di Dennis e Angelo

[image]<https://user-images.githubusercontent.com/30607/107863371-3a56b000-6e54-11eb-8e1e-63d498ee4e02.png>

**Comment by angelogulina** [comment]
@aborruso ecco qui i file :)

| FB Post | FB Cover | IG Post |
|-|-|-|
|![2021-02-14-valore-dati-FB](https://user-images.githubusercontent.com/4223655/107887014-9593ab80-6f03-11eb-92a2-58727c78df25.jpg)|![2021-02-14-valore-dati-FB-cover](https://user-images.githubusercontent.com/4223655/107887012-93c9e800-6f03-11eb-951c-1511f452a55d.jpg)|![2021-02-14-valore-dati-IG](https://user-images.githubusercontent.com/4223655/107887015-962c4200-6f03-11eb-9491-97edeedbc66b.jpg)

**Comment by aborruso** [comment]
Grazie
