### ISSUE TITLE
Problema con ordine dei giornalisti

### ISSUE THREAD

**Issue by nelsonmau** [opendatasicilia/ods2021#11]
lo segno per me. 
Al momento noi possiamo erogare l'evento per i giornalisti, perché noi useremo streamyard per fare live su youtube e facebook, mentre loro usano zoom. 

[leggo però che](https://support.streamyard.com/hc/en-us/articles/360052428952-Can-I-Connect-Zoom-to-StreamYard-)
> You cannot stream StreamYard into a Zoom meeting, as Zoom is not a supported destination at this time.

**Comment by aborruso** [comment]
Ciao Andre,
streamyard sarà soltanto regia.

L'evento sarà live su youtube, e quello sarà il canale anche per la chat.

Quindi non lo vedo il problema.

**Comment by pcmasuzzo** [comment]
Non capisco il problema, @nelsonmau
Non potrebbero prender parte da canale YT?

**Comment by nelsonmau** [comment]
@pcmasuzzo @aborruso non capite/vedete il problema, perché l'ho spiegato male, colpa mia sorry.

Devono registrare chi è presente e chi segue l'evento dall'inizio alla fine. Se accade, attribuiscono i crediti per la formazione professionale continua (obbligatoria per i giornalisti). Con zoom o simili possono mappare i partecipanti uno ad uno, con YT e FB no. 

ne parliamo un attimo nella prox riunione, scusate il misunderstanding, colpa mia

per la cronaca, adesso da streamyard si può fare streaming su queste piattaforme. C'è un opzione custom come vedete (server RTMP) ma da una prima ricerca sembra non applicabile per zoom. 

![2021 02 27-streamyard com](https://user-images.githubusercontent.com/1769578/109385705-21d7a280-78f6-11eb-801a-2cd4d59995c0.png)

**Comment by pcmasuzzo** [comment]
Discusso e chiarito. Chiudo.
