### ISSUE TITLE
Raccolta disponibilità gestione regia

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/ods2021#12]
Per la gestione del live sarà necessario che ci sia qualcuno che gestisca i titoli, gli schermi da mettere in primo piano, i commenti, ecc..
Alzi la mano qui, chi è disponibile a farlo. Non vi vogliono competenze specifiche, ma è meglio che sia qualcuno abituato a usare applicazioni web e meglio ancora (nel caso lo dica) chi ha qualche esperienza con i live video online.

Prima di rispondere, aspettate che invii il messaggio sulla riunione di ieri in mailing list

**Comment by pcmasuzzo** [comment]
A oggi disponibili sono:

> @aborruso 
> @gpirrotta 
> @angelogulina 
> @cirospat 

Io provo a partecipare a riunione regia, cosi' da fare un _jump in_ in caso serva un backup.
