### ISSUE TITLE
Preparare note di testo per chi farà il chairpeople

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/ods2021#13]
Ci sono sicuramente delle cose che i chairpeople dovranno ribadire periodicamente. Ad esempio:

- che l'evento è registrato;
- che i commenti si possono fare live così e colà;
- che ogni intervento dura x minuti e poi ci saranno altri x di domande;
- che si stacca alle y e si riprende qui..

Costruiamo insieme il documento di note qui<br>
<https://docs.google.com/document/d/1PvHvbf6mHJYuK2LYzwwPDQpytqlafFs4TTaZvsx1wS0/edit?usp=sharing>

Se qualcuna/o si vuole intestare la cosa, BENE!

Per comprendere meglio questo messaggio, meglio aspettare che invii in mailing list il messaggio sulla riunione di ieri.

**Comment by pcmasuzzo** [comment]
Ho sviluppato le note qui: https://docs.google.com/document/d/1PvHvbf6mHJYuK2LYzwwPDQpytqlafFs4TTaZvsx1wS0/edit# 

Chiedo feedback - dobbiamo mandare email asap/
ping @gpirrotta @aborruso @nelsonmau @dataibi

**Comment by pcmasuzzo** [comment]
Testo rimane online in modalita' view. Approvato, inviato. Chiudo.
