### ISSUE TITLE
Predisporre testo da inviare ai/alle relatori/relatrici

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/ods2021#16]
Sarà necessario predisporre un testo email con:

- [ ] il programma con la scaletta
- [ ] le modalità con cui si va online
- [ ]  ....

Scriverlo qui <https://docs.google.com/document/d/1Mr4no770kp_ptMrUtPNv8xVB1lFDu-4ayvXS-k81-fI/edit?usp=sharing>

Per comprendere meglio questo messaggio, meglio aspettare che invii in mailing list il messaggio sulla riunione di ieri.

**Comment by pcmasuzzo** [comment]
Ho scritto il testo qui: https://docs.google.com/document/d/1Mr4no770kp_ptMrUtPNv8xVB1lFDu-4ayvXS-k81-fI/edit#

Chiedo feedback/ anche questo deve essere inviato asap.
ping @aborruso @nelsonmau @dataibi @gpirrotta

**Comment by gpirrotta** [comment]
* [x] revisione testo
* [x] creato il gruppo Telegram per la Live
* [x] inserito il link del gruppo Telegram nel doc
* [x] inserito il link Youtube

**Comment by pcmasuzzo** [comment]
Testo rimane online in modalita' view. Approvato, inviato. Chiudo.
