### ISSUE TITLE
Predisporre testo da mandare a tutte le persone iscritte su Eventbrite

### ISSUE THREAD

**Issue by pcmasuzzo** [opendatasicilia/ods2021#20]
Bisogna scrivere un testo da mandare a tutti gli iscritti via Eventbrite - https://www.eventbrite.com/e/biglietti-ods2021-il-raduno-2021-di-open-data-sicilia-141616963149 

Ci lavoro qui: https://docs.google.com/document/d/1NA3bo9EWAJAoCriTbe2uNEV90ukpJmQO_fvR8ewNp8c/edit

**Comment by pcmasuzzo** [comment]
Fatto / ping anche qui 
@aborruso @gpirrotta @dataibi e soprattutto @picomiles

**Comment by gpirrotta** [comment]
* [x] Inserito nel doc il link per la diretta su youtube

**Comment by pcmasuzzo** [comment]
Testo finito, messaggio inviato, chiudo.
