### ISSUE TITLE
Predisposizione form per invio proposte

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/ods2021#3]
@gpirrotta lo predisponi a partire da questo testo <https://docs.google.com/document/d/1VVhCa96G4B0o6353QcFr4151_aJgdxo3IN8_-xUbVRk/edit?ts=60210b85#heading=h.ibob8fgrkqpe>?

Grazie

**Comment by gpirrotta** [comment]
Creato e link inserito in homepage

**Comment by aborruso** [comment]
Hai fatto molto di più.

GRAZIE
