### ISSUE TITLE
proposta di keynote

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/ods2021#8]
Paola ha lanciato la proposta e Andrea D'Eramo ha proposto di affidarlo a qualcuno del mondo del giornalismo, che nel 2020 ha fatto spesso un uso "nuovo" dei dati.

Ci è sembrata una buona idea e assegniamo ad @nelsonmau  di pensare a qualche candidata/o.

Vale che se vengono altre idee, c'è ancora tutto lo spazio per accoglierle.

**Comment by nelsonmau** [comment]
ok mi faccio un elenco in testa e alla prossima call vi faccio delle proposte

chiaramente quella giornalistica è un'ipotesi, ma nel frattempo spero che emergano altre idee

grazie!

**Comment by pcmasuzzo** [comment]
- che conseguenze ha avuto e continua ad avere usare i dati per fare giornalismo? Oltre al giornalismo che diventa sempre più "di precisione", in che modo usare i dati per raccontare le notizie ha cambiato la comunicazione e il rapporto con le lettrici e i lettori? Un giornalismo più lento, fatto di analisi accurate, fact checking, metodologie aperte, paga? Se sì, in che modo?

**Comment by aborruso** [comment]
Sarà Isaia Invernizzi

**Comment by pcmasuzzo** [comment]
Concordato e pianificato, chiudo.
